[package]
name = "flagger-entities"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flagger-types = { path = "../types" }
mongodb = "2.2.2"
serde = { version = "1" }